import turtle as tur

tur.width(4)

def drawRoof():
    tur.width(8)
    tur.begin_fill()
    tur.fillcolor("#ea6d6c")
    tur.seth(180)
    tur.forward(200)
    tur.seth(240)
    tur.forward(100)
    tur.seth(0)
    tur.forward(200)
    tur.seth(60)
    tur.forward(100)
    tur.end_fill()
    tur.seth(-60)
    tur.forward(100)
    tur.width(4)
    tur.seth(180)
    tur.forward(100)

def drawWalls():
    tur.seth(-90)
    tur.forward(120)
    tur.seth(180)
    tur.forward(200)
    tur.seth(90)
    tur.forward(120)
    tur.seth(0)
    tur.forward(300)
    tur.seth(-90)
    tur.forward(120)
    tur.seth(180)
    tur.forward(100)

def rel_pos(x, y):
    tur.penup()
    tur.goto(tur.pos() + (x, y))
    tur.pendown()

def drawDoor():
    tur.color("#004080")
    tur.width(5)
    tur.forward(80)
    tur.begin_fill()
    tur.fillcolor("#b88a61")
    tur.seth(90)
    tur.forward(80)
    tur.seth(180)
    tur.forward(40)
    tur.seth(-90)
    tur.forward(80)
    tur.end_fill()
    rel_pos(25, 40)
    tur.width(4)
    tur.circle(5)

def drawWindows():
    tur.begin_fill()
    tur.color("#004080")
    tur.fillcolor("#8ed9f3")
    tur.seth(-90)
    tur.width(5)
    tur.forward(15)
    tur.seth(180)
    tur.forward(30)
    tur.seth(90)
    tur.forward(30)
    tur.seth(0)
    tur.forward(30)
    tur.seth(-90)
    tur.forward(15)
    tur.end_fill()
    tur.width(2)
    tur.seth(180)
    tur.forward(30)
    tur.backward(15)
    tur.seth(90)
    tur.forward(15)
    tur.backward(30)

def drawHouse():
    drawRoof()
    drawWalls()
    drawDoor()
    rel_pos(-50, 0)
    drawWindows()
    rel_pos(135, 15)
    drawWindows()
    rel_pos(105, 25)
    drawWindows()
    tur.done()
    rel_pos(-250, 250)
    tur.color("#009900")

drawHouse()
tur.mainloop()
